# Generated by Django 6.0.4 on 2026-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='studytask',
            name='preferred_time',
            field=models.CharField(default='Evening', max_length=20),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='hours',
            field=models.FloatField(),
        ),
    ]
